sudo: true
dist: xenial
services:
  - docker
language: python
python:
  - '3.7'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --upload --pdf LDM-722.pdf --lsstdoc LDM-722.tex --env=travis --ltd-product ldm-722"
env:
  global:
    - secure: "MmaHq52mnN32Vp70k65E9wOj+cpblRvWRk9n+z5xwyvyfvJdMg0/AxFAP+SIELVZrEZ+830CKoU+Of9WWkQPtPYKu2EpxTqXXylBdG4ZUwlGBR8jBY0A2GogozvaeJ+fZkKU7FHT9CxaH45pHb5HxCcfuvxf+KzyZyhiQwxJcMoyopCPh5wPkc0rFKt6tK0hskpY/sEhGVbOpPo2l7PGlJq9pIcGHlW+rRLgJibxkqg6Txw09WfnglV0zPKJjEGiENEZjKTu1Tl1sq0ikByWtGgpmIsStTvB8q+8MMBqVLuTgnAQqNiHchetZDcRtsjo3uKETVBXP5xwlOYpeoP3Z5a8TB8t/2bSZ+FNrgFvIvDOzN/4cSk93S+N7S2CkfyCW7JbuBF5phZo7rlOS4bA67Wh1yNQ8FS8bPb5RZ8tL5SNCEL9Z4DmDX7n+oynz3xKsWQwdHw/UFNC1xKSu9dUTrE1lsuizU7Jow34UJPRAAZgdeY//o8++TrzjeOC2CEG3UpGMXMTGg04vj3JL5kgSEBg+niY1FdQhZelK41TQUsxAOCJ9G1on2XOe3OxN/l4zT561bHW6omUJYUn/ccpOkF4MqMbcr/j9o91mBISULn9BnIu5gk1PuHc8/eeKCgUgbS+HjL464GoTG6cJHo3Xk/DDkPmN5KNua3P4GrpDVA="
    - secure: "WCw53bsxxdMJ7BhsR8TM8k5lTaN8X2oACrpwtYSP5peLLgKvX/mFBzHAwLBI/UBAARXN200v+8KJFAZ4RIKeHkKw4nFbuwTdKi1QIa0TWvEvSUZ2HUaGLIRVwFHZP6sLWsqBl7mrmfnb2UvJTKn31d/hq7Lh3cxDYctmSl5qvE2leBIjkDRzjTxluVuakj+Fs0bkhHModG6UXfOBBlXjKvdw84POANjPbFcOuGn/J6zZonsAd+rpPtcQu2ZWsWAuu3fXbbthpOlzM55eQbG/JrjRkwfSBE2qf2R9OBwS/9wlvz/1F9RkIhA/92dA26m824nKhovHLk8Km2IaMHM1UkCkgn7+T3aWMjHqrUHldTiQqjwiQgSlvSvcbPFH49oYMPNqI1U3IJDoF1nlAqDY/9XaxZExlliYbS9KxB32RBt8iZr0ktPmlb3BZsOGyPz+es+4ZpjMhp95WpzRbkPXqkDPM06N5B9+Cf2sHGiCR3nsRbBZCAkXaTgEDy8NqgaeBED6bWYaDMMhAAWzeAgGPyeEdA7d/3Yz5I4aQylEr6OUIjvDWCnxugoG5ViAcUrHGAhAyw8AnqdQvkazxAeBeTVVhnLZco+VF7xMZ0zxFsPR2J+BzecOQBy1hnSWc6fID8L5p4dF0bFdgCPdhJFa6ZQcSfHSS8WcU9vfQfRelAM="
